# docker-compose.yml
version: "2"
services:
  quasartcomp:
    #    image: quasartcomp:1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
      # volumes:
      # - /Users/kbs/git/peladonerd/varios/1/www:/usr/share/nginx/html:ro
      # - //d/storeDocker/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=tcomp.apps.com.pe,www.tcomp.apps.com.pe
      - LETSENCRYPT_HOST=tcomp.apps.com.pe,www.tcomp.apps.com.pe
      - LETSENCRYPT_EMAIL=kevin.silva.095@gmail.com
networks:
  default:
    external:
      name: nginx-proxy_default
